images:
    kubeconfigWriterImage: vincent178/tekton-kubeconfigwriter:0.8.0
    credsImage: vincent178/tekton-creds-init:0.8.0
    gitImage: vincent178/tekton-git-init:0.8.0
    nopImage: vincent178/tekton-nop:0.8.0
    bashNoopImage: vincent178/tekton-bash:0.8.0
    gsutilImage: vincent178/tekton-gsutil:0.8.0
    entrypointImage: vincent178/tekton-entrypoint:0.8.0
    imagedigestExporterImage: vincent178/tekton-imagedigestexporter:0.8.0
    prImage: vincent178/tekton-pullrequest-init:0.8.0
    buildGcsFetcherImage: vincent178/tekton-gcs-fetcher:0.8.0
    controllerImage: vincent178/tekton-controller:0.8.0
    webhookImage: vincent178/tekton-webhook:0.8.0
pipelines:
    namespace: tekton-pipelines
    controller:
        replicas: 1
    webhook:
        replicas: 1
    pvc:
        size: 5Gi
