version: 2
jobs:
  build:
    docker:
      - image: vincent178/circlecibase:latest
    working_directory: /go/src/github.com/vincent178/charts
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: go run main.go
