version: 2
jobs:
  build:
    docker:
      - image: vincent178/circlecibase:latest
    working_directory: /go/src/github.com/vincent178/charts
    steps:
      - add_ssh_keys
      - checkout
      - setup_remote_docker
      - run: git config --global user.email "vh7157@gmail.com"
      - run: git config --global user.name "vincent178"
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: go run main.go
